Notes tab
Public-Health-Scotland/COVID-19-Publication-Dashboard pull request #115
Opened 2022-05-19 08:10 UTC by seonaidmore

I've added the notes tab plus tried to remove some notes, but some are within a function and defined as "subheading", can't see an alternative except replacing the text with paste0(""), what do you think?

2022-05-19 09:03 UTC, RosalynLP requested changes
It's looking really good!
 I've removed the stray bits of text and also just fixed a couple of typos. Before merging we need to:

- Fix the links down the left hand side of the notes tab
- Merge master
-
I'll try and merge master in now as it could be a bit messy.

2022-05-30 08:43 UTC, RosalynLP approved these changes
Looks great, just recommented the setwd as it won't deploy with that uncommented

2022-05-30 08:43 UTC, RosalynLP commented on shiny_app/global.R
> +setwd("/conf/PHSCOVID19_Analysis/COVID-19-Publication-Dashboard/shiny_app")
Have commented this out again

2022-05-30 08:46 UTC, rubenv95 commented on shiny_app/global.R
> +setwd("/conf/PHSCOVID19_Analysis/COVID-19-Publication-Dashboard/shiny_app")
Oh yeah cool, didn't spot that, thanks

2022-05-30 08:59 UTC, merged